### ISSUE TITLE
blog article: 4b if statements - correction

### ISSUE THREAD

**Issue by marcelpetrick** [andreasjhkarlsson/andreasjhkarlsson.github.io#1]
Hello,
I am reading right now https://andreasjhkarlsson.github.io//jekyll/update/2023/12/27/4-billion-if-statements.html and it states that  `Python (thanks to the visionary genius of Ross van der Gussom).`

But the guy's name is `Guido van Rossum`.

Actually I wanted to fix this by PR, but can't find the file for your article. Enlighten me please.

Greetings from Munich, Marcel

**Comment by marcelpetrick** [comment]
Also: the article is quite fun! :)

**Comment by jasonycw** [comment]
It is here: https://github.com/andreasjhkarlsson/andreasjhkarlsson.github.io/blob/gh-pages/_posts/2023-12-27-4-billion-if-statements.markdown

**Comment by marcelpetrick** [comment]
Thank you, have prepared the PR.
